# Generated by Django 5.2.6 on 2025-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('destination', models.TextField(max_length=250)),
                ('create_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
